// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from "eslint-plugin-storybook";

import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Provider SDKs may only be imported inside src/adapters/** (domain rule 12:
// "Provider SDKs must not leak into domain or frontend code"). Grows as
// providers are adopted per docs/decisions/ADR-006-concrete-infrastructure.md.
const providerImportPatterns = [
  "@ai-sdk/*",
  "@vercel/blob",
  "@vercel/blob/*",
  "better-auth",
  "better-auth/*",
];

// The Vercel AI SDK (`ai` package) is matched by an ANCHORED regex rather than a
// gitignore-style group, for the SAME reason as the `workflow` package below: a
// bare `ai`/`ai/*` group also matches internal modules under an `ai/` directory
// (e.g. `@/adapters/ai/*`, `@/application/ai/*`, `./ai/generate-structured`).
// `^ai(/.*)?$` matches only the real package and its subpaths, so the gateway
// adapter is fenced to src/adapters/ without colliding with our own `ai/` dirs.
const aiPackageRestriction = {
  regex: "^ai(/.*)?$",
  message:
    "The Vercel AI SDK (`ai`) may only be imported inside src/adapters/ai/ (domain rule 12). Depend on the LanguageModel port instead.",
};

// The Vercel Workflow DevKit (`workflow` package) is matched by an ANCHORED
// regex rather than a gitignore-style group: a bare `workflow` group would also
// catch internal modules whose basename is `workflow` (e.g. `@/domain/workflow`,
// `./workflow`). `^workflow(/.*)?$` matches only the real package and its
// subpaths (`workflow`, `workflow/api`, `workflow/next`), so the WDK adapter is
// still fenced to src/adapters/ without colliding with domain module names.
const workflowPackageRestriction = {
  regex: "^workflow(/.*)?$",
  message:
    "The Vercel Workflow (WDK) package may only be imported inside src/adapters/ (domain rule 12). Depend on the JobDispatcher port instead.",
};

// Database driver + ORM packages may only be imported inside src/db/** (the
// single DB entry point, schema, migrations, repositories) and src/adapters/**
// (the Better Auth adapter persists through the same db). Everything else
// depends on the repository ports in src/application/, never on Drizzle rows or
// a raw driver. ADR-005/006; M2 boundary.
const databaseImportPatterns = [
  "drizzle-orm",
  "drizzle-orm/*",
  "pg",
  "@electric-sql/pglite",
];

const providerRestriction = {
  group: providerImportPatterns,
  message:
    "Provider SDKs may only be imported inside src/adapters/ (domain rule 12). Depend on a Storylight port instead.",
};

const databaseRestriction = {
  group: databaseImportPatterns,
  message:
    "Drizzle/DB drivers may only be imported inside src/db/ or src/adapters/. Depend on a repository port (src/application/ports) instead.",
};

// ESLint flat config merges rules by "last object wins" for any file a config
// object matches, so the two boundaries are expressed as NON-overlapping file
// regions rather than two objects both matching src/**:
//   - src/adapters/**  → no restriction (the only place providers + drivers live)
//   - src/db/**        → drivers allowed, providers still forbidden
//   - everything else  → both forbidden (domain, application, components, lib)
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Non-adapter, non-db code: neither provider SDKs nor DB drivers.
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/adapters/**", "src/db/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            providerRestriction,
            aiPackageRestriction,
            workflowPackageRestriction,
            databaseRestriction,
          ],
        },
      ],
    },
  },
  {
    // The DB layer may use Drizzle/drivers, but never a provider SDK.
    files: ["src/db/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            providerRestriction,
            aiPackageRestriction,
            workflowPackageRestriction,
          ],
        },
      ],
    },
  }, // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build artifacts (gitignored) that ESLint's flat config does not skip on
    // its own.
    "storybook-static/**",
    "drizzle/**",
    // Generated by withWorkflow() at build time (gitignored); ships its own
    // eslint-disable, which our config would otherwise flag as unused.
    "src/app/.well-known/**",
  ]),
  ...storybook.configs["flat/recommended"],
]);

export default eslintConfig;
